services:
  frontend:
    ports:
      - "4201:4200"
    volumes:
      - ../frontend:/app
      - frontend-node-modules:/app/node_modules

  backend:
    ports:
      - "3000:3000"
    volumes:
      - ../backend:/app
      - backend-node-modules:/app/node_modules

  postgres:
    ports:
      - "5432:5432"

  hapi-fhir:
    ports: []

  hapi-fhir-cors:
    ports:
      - "8081:8080"

  elasticsearch:
    ports:
      - "9200:9200"

  snowstorm:
    ports: []

  snowstorm-cors:
    ports:
      - "8082:8080"

  snowstorm-browser:
    ports:
      - "8083:80"

volumes:
  frontend-node-modules:
  backend-node-modules:
